<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    <link rel="stylesheet" href="<?= assets_url() ?>css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?= assets_url() ?>css/all.min.css" />
</head>

<body>
    <div class="container text-center">
        <div class="row">
            <div class="col m-5 p-5">
                <?php if ($deletedCount) : ?>
                    <span class="text-success"> Contact delete successfully !</span>
                <?php else : ?>
                    <span class="text-danger"> Contact Not exists !</span>
                <?php endif; ?>

            </div>
        </div>
        <div class="row">
            <div class="col mt-3">
                <div class="d-flex justify-content-center">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);">
                        <g>
                            <circle stroke-linecap="round" fill="none" stroke-dasharray="50.26548245743669 50.26548245743669" stroke="#000000" stroke-width="8" r="32" cy="50" cx="50">
                                <animateTransform values="0 50 50;360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1s" type="rotate" attributeName="transform" />
                            </circle>
                            <circle stroke-linecap="round" fill="none" stroke-dashoffset="36.12831551628262" stroke-dasharray="36.12831551628262 36.12831551628262" stroke="#be0027" stroke-width="8" r="23" cy="50" cx="50">
                                <animateTransform values="0 50 50;-360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1s" type="rotate" attributeName="transform" />
                            </circle>
                            <g />
                        </g><!-- [ldio] generated by https://loading.io -->
                    </svg>
                </div>
                <script>
                    setTimeout(() => {
                        location.href = "<?= site_url() ?>"

                    }, 1000);
                </script>
                <div class="mt-3">Redirecting to Home ....</div>
            </div>
        </div>
    </div>

</body>

</html>